name: Deploy Quasar SPA

on:
  push:
    branches:
      - main  # Change to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Change to your desired Node.js version

    - name: Install Quasar CLI
      run: npm install -g @quasar/cli

    - name: Install dependencies
      run: npm install

    - name: Build Quasar SPA
      run: quasar build

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          # Create a directory on the server to store the app
          mkdir -p ~/tenant.contactcentre
          
          # Transfer the built app files to the server using SCP
          scp -i ${{ secrets.PRIVATE_KEY_PATH }} -r ./dist/spa/* ${username}@${host}:~/tenant.contactcentre

          # SSH into the server
          cd ~/tenant.contactcentre && ls && npm install pm2 -g && pm2 start npm --name contactcentre-tenant -- start
